{
  "hosting": {
    "public": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**",
      "**/*.bat",
      "**/*.md",
      "**/*.txt",
      ".github/**",
      "subir.bat",
      "reparar_y_subir.bat"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
